oc_platform_home:
    path:    /platform
    defaults:
        _controller:    OCPlatformBundle:Advert:index

oc_platform_view:
    path:    /platform/advert{id}
    defaults:    OCPlatformBundle:Avert:view

oc_platform_add:
    path:    /platform/add
    defaults:    OCPlatformBundle:Avert:add
